lst = []
lst.append(1)
lst.append(2)
lst.append(3)
print(lst)  
lst.extend([5, 6, 7])
print(lst)  
lst.insert(3, 4)
print(lst) 
lst.pop()
print(lst)  
lst.remove(6)
print(lst) 
index = lst.index(3)
print(index) 
lst.reverse()
print(lst) 
new_lst = lst[:3]
print(new_lst)  
lst = [2, 4, 1, 5, -1]
sorted_lst = sorted(lst)
print(sorted_lst)  
lst.sort()
print(lst) 